### ISSUE TITLE
Porting to other languages

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/ruby-discoverd#22]
Is it worth porting this now, or will the protocol be replaced by duplex in the near future? @progrium

**Comment by progrium** [comment]
The tests for rpcplus are passing against Duplex right now. This means it's a near drop in replacement that should work just the same. However Duplex is not intended to be protocol (since the protocol is very simple), it's a Go library until we prove it works, then it will be ported to C and make bindings in other languages much easier. But if we use Duplex in Flynn, that will break Ruby support... so there's a sort of chicken or the egg situation. Unless we support both mechanisms for a period?

**Comment by titanous** [comment]
@progrium We already use the [comborpc](https://github.com/flynn/rpcplus/blob/master/comborpc/server.go) package to implement gob+json rpcplus, so running duplex+json rpc seems viable.

**Comment by progrium** [comment]
Hmm, except it doesn't play perfectly with existing RPC interfaces, so it
might not work as cleanly as you'd expect. But it might work...

On Mon, Apr 28, 2014 at 10:12 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> @progrium https://github.com/progrium We already use the comborpchttps://github.com/flynn/rpcplus/blob/master/comborpc/server.gopackage to implement gob+json rpcplus, so running duplex+json rpc is viable
> I think.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/ruby-discoverd/issues/22#issuecomment-41638026
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
@progrium I don't have the bandwidth to work on anything related to duplex right now, but feel free to send pull requests if you decide to test it out with Flynn.

**Comment by progrium** [comment]
I figure as much!

On Mon, Apr 28, 2014 at 10:47 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> @progrium https://github.com/progrium I don't have the bandwidth to
> work on anything related to duplex right now, but feel free to send pull
> requests if you decide to test it out with Flynn.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/ruby-discoverd/issues/22#issuecomment-41639320
> .

## 

Jeff Lindsay
http://progrium.com
